version: "3.8"

services:
  nginx:
    build:
      context: ./requierements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception-net
    depends_on:
      - wordpress

  mariadb:
    env_file: .env
    build:
      context: ./requierements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - mariadb_db:/var/lib/mysql
    restart: always
    networks:
      - inception-net
    command: ./script.sh

  wordpress:
    env_file: .env
    depends_on:
      - mariadb
    build:
      context: ./requierements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    networks:
      - inception-net
    volumes:
      - wordpress:/var/www/html
    ports:
      - "${WP_PORT}:9000"

networks:
  inception-net:
    driver: bridge

volumes:
  mariadb_db:
    driver: local
    driver_opts:
      type: none
      device: /home/kcharbon/data/wordpressDB
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/kcharbon/data/wordpressData
      o: bind
#utiliser le dossier secret pour les mdp
