listen=YES
anonymous_enable=NO
local_enable=YES
write_enable=NO

#activation des logs
xferlog_enable=YES
xferlog_std_format=YES
xferlog_file=/var/log/vsftpd.log

ftpd_banner="WELCOME TO SKYLAND"

#lecture des fichiers
anon_umask=022 
chroot_local_user=YES
local_root=/var/www/html


pasv_min_port=21000
pasv_max_port=21010
