CREATE DATABASE IF NOT EXISTS ${MARIADB_DATABASE};
CREATE USER IF NOT EXISTS  ${MARIADB_USER}@'%' IDENTIFIED BY ${DB_PASSWORD};
CREATE USER IF NOT EXISTS  ${MARIADB_USER2}@'%' IDENTIFIED BY ${DB_PASSWORD2};
GRANT ALL PRIVILEGES ON ${MARIADB_DATABASE}.* TO ${MARIADB_USER}@'%' WITH GRANT OPTION;
ALTER USER 'root'@'localhost' IDENTIFIED BY ${MARIADB_ROOT_PASSWORD};
FLUSH PRIVILEGES;